language: go

go:
  - 1.12.x

before_install:
  - go get -t -v .
  - go get github.com/mattn/goveralls

env:
  - GO111MODULE=on DATA1=true DATA2=false DATA3=9 DATA4=0 DATA5=3m5s EMPTY="" DATA6="aGVsbG8=" ONLYENV=1

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
