language: go

go:
  - 1.10.x
  - 1.11.x

before_install:
  - go get github.com/mattn/goveralls

env:
  - DATA1=true
  - DATA2=false
  - DATA3=9
  - DATA4=0
  - DATA5=3m5s
  - EMPTY=""

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
