name: Test
on:
  push:
  pull_request:
jobs:
  runner-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.20']
    name: Go ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - run: go get -t -v ./...
    - run: go test -coverprofile=coverage.txt -covermode=atomic ./...
      env:
        DATA1: "true"
        DATA2: "false"
        DATA3: "9"
        DATA4: "0"
        DATA5: "3m5s"
        EMPTY: ""
        DATA6: "aGVsbG8="
        DATA7: "1.25"
        ONLYENV: "1"
    - uses: codecov/codecov-action@v3
